export const editorOptions = {
    autoClosingBrackets: "always",
    autoClosingQuotes: "always",
    suggestOnTriggerCharacters: true,
    quickSuggestions: true,
    autoIndent: "full",
    contextmenu: true,
    fontFamily: "monospace",
    fontSize: 13,
    lineHeight: 24,
    hideCursorInOverviewRuler: true,
    matchBrackets: "always",
    scrollbar: {
      horizontalSliderSize: 4,
      verticalSliderSize: 18,
    },
    // selectOnLineNumbers: true,
    roundedSelection: false,
    readOnly: false,
    cursorStyle: "line",
    automaticLayout: true,
    wordWrap: "on",
    minimap: true,
  };