FROM openjdk:latest

WORKDIR /app

COPY javaTLE.sh /app/entrypoint.sh

RUN apk add --no-cache dos2unix && dos2unix /app/entrypoint.sh

RUN chmod +x /app/entrypoint.sh

ENTRYPOINT ["/app/entrypoint.sh"]

CMD ["sh", "-c", "javac Main.java && java Main < input.txt"]
