FROM python:latest

WORKDIR /app

COPY pythonTLE.sh /app/entrypoint.sh

RUN apt-get update && apt-get install -y dos2unix && dos2unix /app/entrypoint.sh

RUN chmod +x /app/entrypoint.sh

ENTRYPOINT ["/app/entrypoint.sh"]

CMD ["python", "Main.py"]
