FROM gcc:latest

WORKDIR /app

COPY tle.sh /app/entrypoint.sh

RUN chmod +x /app/entrypoint.sh

ENTRYPOINT ["/app/entrypoint.sh"]

CMD ["sh","-c","g++ code.cpp -o code && ./code < input.txt","timeout","1"]
